/**
 * @file    	gtest_befriend_hook_macros.h
 * @author  	Callum Noble
 * @date    	December 2013
 * @brief     	Hook macros that forward declare and grant friendship to related 
 * 				gtest tests and fixtures. Header files including this must also include
 * 				headers generated by generate_gtest_befriend_macros.pl
 */

#ifndef GTEST_BEFRIEND_HOOK_MACROS_H
#define GTEST_BEFRIEND_HOOK_MACROS_H

#include <boost/preprocessor/cat.hpp>

#define GTESTS_FORWARD_DECLARE(x) x##_FD
#define GTESTS_BEFRIEND(x) x##_FR

#endif
